name: Coverage

# Notes:
# - The os job installs phmutest in a virtual environment.
# - The coverage job installs phmutest dependencies, but does
#   not install phmutest.  It imports phmutest from the checked
#   out src folder set by the environment variable PYTHONPATH.
# - The inspect job installs phmutest.
on:
  workflow_dispatch:

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      id: setuppython
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install coverage, dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r tests/requirements.txt

    - name: Coverage report
      run: |
        coverage erase
        # Get coverage for no extras installed.
        coverage run --branch --source=src --append -m phmutest --version
        coverage run --branch --source=src --append -m pytest tests/test_color.py tests/test_traceback.py
        python -m phmutest tests/md/does_not_print.md --generate dev/test_temptestfile.py
        # This script installs the extras and handles phmutest runs with failing tests.
        chmod u+x .github/workflows/coverage.sh
        ./.github/workflows/coverage.sh
        coverage run --branch --source=src --append -m pytest tests
        coverage report --show-missing --precision=2
        coverage xml
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml # optional
        flags: python-${{ steps.setuppython.outputs.python-version }} # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
